test_results = [
    [
        (
            "COM SCI 32",
            "Edwin Ambrosio",
            {
                "post": 0,
                "partner": 0,
                "slide": 6,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 32",
            "Kung-Hua Chang",
            {
                "post": 0,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 32",
            "Carey Nachenberg",
            {
                "post": 3,
                "partner": 0,
                "slide": 36,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 32",
            "Michael Shindler",
            {
                "post": 0,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 32",
            "David Smallberg",
            {
                "post": 3,
                "partner": 0,
                "slide": 19,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
    ],
    [
        (
            "COM SCI 33",
            "Paul Eggert",
            {
                "post": 1,
                "partner": 0,
                "slide": 7,
                "together": 1,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "Parvaneh Ghaforyfard",
            {
                "post": 0,
                "partner": 0,
                "slide": 4,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "Jochen Haber",
            {
                "post": 0,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "Ani Nahapetian",
            {
                "post": 0,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "Anthony Nowatzki",
            {
                "post": 4,
                "partner": 0,
                "slide": 18,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "L Pouchet",
            {
                "post": 0,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "Glenn Reinman",
            {
                "post": 2,
                "partner": 0,
                "slide": 7,
                "together": 1,
                "attendance": 0,
                "pair": 0,
                "upload": 1,
            },
        ),
        (
            "COM SCI 33",
            "John Rohr",
            {
                "post": 1,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
        (
            "COM SCI 33",
            "David Smallberg",
            {
                "post": 0,
                "partner": 0,
                "slide": 0,
                "together": 0,
                "attendance": 0,
                "pair": 0,
                "upload": 0,
            },
        ),
    ],
]
